### PR TITLE
fixed for large dataset

### PR DESCRIPTION
**Pull request by dongnizh**
Hi, @chrismattmann Try it. I changed it binding like **" testdata/circle5.json" and " testdata/clusters5.json"**. You can make it changed to your file name. Any suggestions?

### CODE REVIEW

**Comment by chrismattmann** [comment]
yay commiting now!

**Comment by chrismattmann** [comment]
I tried this and didn't work @dongnizh  :(

**Comment by chrismattmann** [comment]
It just hangs and never shows the cluster how long does it take? Tried in chrome and on safari

**Comment by dongnizh** [comment]
@chrismattmann  It works fine on my chrome and safari. But it has a little delay to load all that nodes. I will show you later on local server. ^_^

**Pull request merged**
